apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: quote-frontend
  template:
    metadata:
      labels:
        app: quote-frontend
    spec:
      containers:
      - name: quote-frontend
        image: aravindad94/quote-frontend:latest
        ports:
        - containerPort: 80
